spring:
  cloud:
    config:
      server:
        git:
          search-paths:
          uri:
      password:
      username:
  application:
    name: config
server:
  port: 9999
eureka:
  instance:
    hostname: config
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
          defaultZone: http://localhost:9093/eureka
